FROM golang:1.21 AS build-stage


WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /my-binary

# Test stage
FROM build-stage AS run-test-stage
RUN  go test -v ./...

# release stage
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /my-binary /my-binary

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT [ "/my-binary" ]